name: Update Releases
on:
  push:
    paths:
      - '.github/workflows/update_releases.yml'

jobs:
  update-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit v1.0.0 --notes "### 🚀 Что добавлено (Features)
          * **Релиз скомпилированной версии:** Программа впервые упакована в удобный \`.exe\` файл. Больше не требуется установленный Python!
          * **Ручной выбор версий аддона:**
            * Добавлена синяя кнопка **\"Версии\"** напротив каждого аддона.
            * Позволяет откатываться на старые стабильные сборки в обход глобальных настроек (незаменимо, если разработчик сломал новую версию аддона под ваш клиент игры).
          * **Премиум дизайн репозитория:** Полностью переписан \`README.md\`, сгенерирован стильный логотип проекта, добавлены интерактивные бейджи.
          * **Автоматизация:** Настроен пайплайн GitHub Actions для автоматического выпуска \`.exe\` файлов." --repo paul2877/WoW-Updater

      - name: Update v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit v1.0.1 --notes "### 🐛 Что исправлено (Bug Fixes)
          * **Критический баг подбора версий (Raider.IO / WeakAuras):** 
          Ранее загрузчик скачивал самую последнюю версию из категории Retail, из-за чего для патча 11.x ошибочно скачивались сборки под Midnight (12.x). 
          Теперь логика ядра полностью переписана: программа выполняет **строгий текстовый поиск** по патчу (например, \`11.0.5\`). Если точное совпадение найдено, скачивается именно этот файл, полностью игнорируя версии для Midnight." --repo paul2877/WoW-Updater
